### ISSUE TITLE
Use the lib  error

### ISSUE THREAD

**Issue by LItterBoy-GB** [winlibs/libffi#3]
ffi.lib(closures.obj) : 找到 MSIL .netmodule 或使用 /GL 编译的模块；正在使用 /LT
CG 重新启动链接；将 /LTCG 添加到链接命令行以改进链接器性能
   正在创建库 fiddle-x64-mswin64_120.lib 和对象 fiddle-x64-mswin64_120.exp
conversions.obj : error LNK2001: 无法解析的外部符号 __imp_ffi_type_void
conversions.obj : error LNK2001: 无法解析的外部符号 __imp_ffi_type_uint8
conversions.obj : error LNK2001: 无法解析的外部符号 __imp_ffi_type_sint8
conversions.obj : error LNK2001: 无法解析的外部符号 __imp_ffi_type_uint16
conversions.obj : error LNK2001: 无法解析的外部符号 __imp_ffi_type_sint16
conversions.obj : error LNK2001: 无法解析的外部符号 __imp_ffi_type_uint32
conversions.obj : error LNK2001: 无法解析的外部符号 __imp_ffi_type_sint32
conversions.obj : error LNK2001: 无法解析的外部符号 __imp_ffi_type_uint64
conversions.obj : error LNK2001: 无法解析的外部符号 __imp_ffi_type_sint64
conversions.obj : error LNK2001: 无法解析的外部符号 __imp_ffi_type_float
conversions.obj : error LNK2001: 无法解析的外部符号 __imp_ffi_type_double
conversions.obj : error LNK2001: 无法解析的外部符号 __imp_ffi_type_pointer
../../.ext/x64-mswin64_120/fiddle.so : fatal error LNK1120: 12 个无法解析的外部
命令

**Comment by ChillMagic** [comment]
@LItterBoy-GB It seems as compiling 'ruby'？
Please ensure that the compile option (like /GL /MD ...) with 'ffi.lib' & program that uses 'ffi.lib' should be same.

**Comment by LItterBoy-GB** [comment]
![default](https://user-images.githubusercontent.com/28385638/38533758-5a5692e8-3cad-11e8-91e7-72d77944daad.png)
Awkward!! I don't know modify it.

**Comment by ChillMagic** [comment]
@LItterBoy-GB I just remembered that, this project (libffi with VC project) have some problem.
The defination of macro `FFI_BUILDING` in compiling is not correct.
https://github.com/winlibs/libffi/blob/master/win32/vc15_x64/libffi/libffi.vcxproj#L65
```
WIN32;NDEBUG;_LIB;%(PreprocessorDefinitions),FFI_BUILDING
```
->
```
WIN32;NDEBUG;_LIB;%(PreprocessorDefinitions);FFI_BUILDING
```
The ';' is incorrectly written to ','.

It may cause some functions's delcare incorrect. (__imp_ffi_XXX but ffi_XXX)

**Comment by LItterBoy-GB** [comment]
@ChillMagic  Thank you. But it is unuseful.
![111](https://user-images.githubusercontent.com/28385638/38545417-95527dce-3cdc-11e8-97f3-55517e8347e9.jpg)

**Comment by ChillMagic** [comment]
@LItterBoy-GB 
- LINK2001 : The symbol has not finded.
- dynamic library (.dll) : `__declspec(dllimport)` with `__imp` header
- static library (.lib) : no `__declspec(dllimport)` & no `__imp`

https://github.com/winlibs/libffi/blob/master/include/ffi.h#L184
```c
#if defined _MSC_VER && !defined FFI_BUILDING
#define FFI_EXTERN extern __declspec(dllimport)
#else
#define FFI_EXTERN extern
#endif
```

I think `ffi.h` is different from compiling `ffi.c` and `conversions.c`.
You can try
```c
#define FFI_EXTERN extern
```
or
```c
#define FFI_EXTERN extern __declspec(dllimport)
```
(delete the `#if #endif`)
In `ffi.h`, and then build two libs.

**Comment by weltling** [comment]
Thanks for the report. Please use static library build. All the other configurations should be likely removed. Some pre compiled bins can be found under https://windows.php.net/downloads/php-sdk/deps/ .

Thanks.

**Comment by LItterBoy-GB** [comment]
@weltling  I use the ffi in VC12(VS2013). There is no.

**Comment by LItterBoy-GB** [comment]
@ChillMagic sorry, I just saw email. I try it.

**Comment by LItterBoy-GB** [comment]
@ChillMagic  It still doesn't work

**Comment by ChillMagic** [comment]
@LItterBoy-GB I'm sorry that I didn't help you. You should check if the conversions.c uses `__imp` or not.

**Comment by LItterBoy-GB** [comment]
@ChillMagic 
"__imp_" is append by VS. 
It wants to  express VS can not find  the implement of  “ffi_type_void”
Still thank you very much.

**Comment by ChillMagic** [comment]
@LItterBoy-GB It's my pleasure.

**Comment by cmb69** [comment]
Change `#if defined _MSC_VER && !defined FFI_BUILDING` to `#if 0` when using ffi.lib.

**Comment by aldveylor** [comment]
You can try adding the code under.
```c
#define FFI_BUILDING
#include <ffi.h>      //just add defintion EFI_BUILDING ahead of including ffi.h

#pragma comment(lib,"libffi.lib")
```
This is the example code.
```c
#include <stdio.h>

#define FFI_BUILDING
#include <ffi.h>

#pragma comment(lib,".\\libffi_release_86.lib")

char* exp_string(double b, int n) {
    double result = 1;
    for (int i = 0; i < n; i++) {
        result *= b;
    }

    char* str = (char*)malloc(sizeof(char) * 50);
    snprintf(str, 50, "%f", result);

    return str;
}

int main() {
    ffi_cif cif;    // 函数调用所需的上下文

    ffi_type* arg_types[2];    // 参数类型指针数组
    void* arg_values[2];    // 参数值指针数组
    ffi_status status;

    // 根据被调用函数的参数类型进行设定.
    arg_types[0] = &ffi_type_double;
    arg_types[1] = &ffi_type_sint32;

    // 这里 ffi_prep_cif 的第三个参数为被调用函数参数数量, 第四个参数为返回值类型的指针.
    if ((status = ffi_prep_cif(&cif, FFI_DEFAULT_ABI, 2, &ffi_type_pointer, arg_types)) != FFI_OK) {
        perror("ffi_prep_cif");
        abort();
    }

    // 设置函数参数.
    double arg_b = 3.14;
    int arg_n = 6;

    arg_values[0] = &arg_b;
    arg_values[1] = &arg_n;

    // 声明返回值存放的变量.
    char* retVal;

    // 交给 libffi 调用这个函数.
    ffi_call(&cif, FFI_FN(exp_string), &retVal, arg_values);

    // 输出结果.
    printf("Function result: %s\n", retVal);

    return 0;
}
```
This is the result.
![image](https://user-images.githubusercontent.com/30283620/81565938-b8b98980-93cc-11ea-867d-df7acbd4c8cb.png)

Does this help?
